[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "london"

# Flare Network configurations
[rpc_endpoints]
flare = "https://flare-api.flare.network/ext/C/rpc"
coston2 = "https://coston2-api.flare.network/ext/C/rpc"

[etherscan]
flare = { key = "${FLARE_API_KEY}", url = "https://flare-explorer.flare.network/api" }
coston2 = { key = "${COSTON2_API_KEY}", url = "https://coston2-explorer.flare.network/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
